#!/usr/bin/env python3
"""Generate coefficients/cost-model-collectives.yaml from AISimulate NCCL sweeps.

The set has 224 entries across five SKUs, four operations, two dtypes and three
rank counts. Hand-writing that many would guarantee the drift this whole exercise
exists to prevent, so the file is generated and the generator is the source of
truth for it. Re-run after an AISimulate update; the diff is the change.

Usage:
    python scripts/emit_collectives.py <aisimulate-data-dir> > \
        coefficients/cost-model-collectives.yaml
"""

from __future__ import annotations

import importlib.util
import os
import sys
from pathlib import Path

_spec = importlib.util.spec_from_file_location(
    "fit_collectives", Path(__file__).parent / "fit_collectives.py"
)
fc = importlib.util.module_from_spec(_spec)
assert _spec.loader is not None
_spec.loader.exec_module(fc)

HEADER = '''# Collective floors and peak rates — every entry from NVIDIA AISimulate.
#
# GENERATED by scripts/emit_collectives.py. Do not edit by hand: 224 entries
# transcribed manually would drift from the sweeps they come from, which is the
# failure this file is generated to avoid. Re-run the generator after an
# AISimulate data update and commit the diff.
#
# Source. AISimulate's comm/nccl/<version>/nccl_perf.parquet, one collection per
# SKU: 256 B to 512 MiB across four operations, two dtypes and 2, 4 and 8 ranks.
# One methodology applied uniformly across parts, which is what makes the
# cross-SKU and cross-width comparisons here meaningful.
#
# Three axes ride in each entry NAME rather than in `scope`, because SCOPE_KEYS
# has no member for operation, dtype or rank count. The scope still carries
# `hardware`, so a coefficient fitted on one part cannot silently price another.
#
# What the measurements show, and why all three axes are needed:
#
#   * OPERATION. On H200 an all-reduce floor is 15.98 us against an all-to-all
#     floor of 7.39 — a reduction synchronizes where a shuffle does not. A single
#     floor for all four operations is wrong in both directions at once.
#   * DTYPE. int8 all-reduce reaches 201 GB/s on H200 where half reaches 132: the
#     reduction arithmetic is in the critical path. A rate with no dtype axis
#     misprices one of the two by 1.5x.
#   * RANK COUNT. all-reduce floors run 6.0 / 9.4 / 16.0 us at 2 / 4 / 8 ranks
#     while all-to-all runs 6.4 / 6.6 / 7.4. The ring-shaped reduction's floor
#     grows with width and the shuffle's barely does, which is the span term the
#     cost model prices — here measured rather than assumed.
#
# A floor is the minimum latency over messages at or below 4 KiB, where latency is
# independent of size. The minimum rather than the median because the sweeps carry
# occasional single-point noise (h100 all-to-all at 4 ranks reads 17.67 us at
# 512 B among neighbours at 6.5 to 7.6) and a floor is a lower bound on achievable
# latency, so a high outlier must not raise it. Each entry records the spread over
# that region so the noise is visible rather than hidden.
#
# A peak rate is the maximum of message_size / latency. Where the sweep had not
# saturated at its largest message the rationale says so and the value is a lower
# bound on the asymptote — which overstates transfer time, the safe direction.
#
# A transition rate is the third parameter, and the reason each configuration has one.
# Pricing a collective as max(size / peak, floor) is right at both ends of the sweep and
# optimistic everywhere between: it understates an 8-rank H200 all-reduce by up to 3.2x
# and an all-gather by up to 3.8x, and that region — roughly 64 KiB to 8 MiB — is where a
# prefill batch's collectives land. The form that fits is
#
#     latency = max(floor + size / transition_rate, size / peak_rate)
#
# which takes the median error over all 136 measured configurations from 1.34x to 1.17x
# and the worst case from 1.83x to 1.51x. Each entry records its own before-and-after
# error so the improvement is visible per configuration rather than only in aggregate.
kind: CoefficientSet
name: cost-model-collectives

coefficients:
'''

# NCCL's dtype names, mapped to the registry's.
DTYPE = {"half": "fp16", "int8": "int8"}


def entry(
    name: str,
    value: float,
    units: str,
    chip: str,
    rationale: str,
    cite: str,
    fitted: bool = False,
) -> str:
    return (
        f"  - {name}:\n"
        f"      value: {value}\n"
        f"      units: {units}\n"
        f"      method: measured\n"
        f"      fitted: {'true' if fitted else 'false'}\n"
        f"      scope: {{hardware: [{chip}]}}\n"
        f"      sources:\n"
        f"        - {{kind: model, cite: \"{cite}\", role: primary}}\n"
        f"      rationale: >\n"
        f"        {rationale}\n"
    )


# The NCCL collection each committed entry cites. Pinned rather than "newest wins":
# AISimulate keeps adding collections, and the newest is not always the richest. NCCL
# 2.30.7, added after these coefficients were generated, carries 60 rows under a narrower
# schema with no `device`/`version` columns, where 2.29.2 carries 504 under the full one.
# Taking the newest would both crash and silently change the citations. Override with
# NCCL_COLLECTION=<version> to fit a different one deliberately.
PINNED_NCCL = {
    "a100_sxm": "2.27.3",
    "a100_pcie": "2.27.3",
    "l40s": "2.27.3",
    "h100_sxm": "2.29.2",
    "h200_sxm": "2.29.2",
    "b200_sxm": "2.29.2",
    "b300_sxm": "2.29.2",
    "gb200": "2.29.2",
}


def _pick_collection(comm: Path, sku: str) -> Path | None:
    """The pinned NCCL collection for `sku`, or None when it is absent."""
    want = os.environ.get("NCCL_COLLECTION") or PINNED_NCCL.get(sku)
    if want is None:
        return None
    path = comm / want
    return path if path.is_dir() else None


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    root = Path(argv[1])
    out = [HEADER]
    total = 0
    for sku, chip in sorted(fc.SKU_TO_CHIP.items()):
        comm = root / sku / "comm" / "nccl"
        if not comm.is_dir():
            continue
        version = _pick_collection(comm, sku)
        if version is None:
            continue
        rows = fc.read_sweep(version)
        device, nccl = rows[0]["device"], rows[0]["version"]
        cite = (
            f"NVIDIA AISimulate systems/data/{sku}/comm/nccl/{version.name}/"
            f"nccl_perf.parquet (NCCL {nccl}, {device})"
        )
        out.append(f"\n  # --- {chip}: {device}, NCCL {nccl} ---\n")
        for g in fc.reduce_sweep(rows):
            if not g.usable:
                continue
            dt = DTYPE.get(g.dtype, g.dtype)
            stem = f"{g.op}_{dt}_{g.ranks}rank_{chip.replace('-', '_')}"
            points = len(g.points)
            out.append(
                entry(
                    f"collective_floor_{stem}",
                    round(g.floor_us, 2),
                    "us_per_transfer",
                    chip,
                    f"Minimum latency over the {g.flat_count} messages at or below "
                    f"4 KiB, where latency is independent of size; that region "
                    f"spans {g.flat_spread:.2f}x, so the minimum rather than the "
                    f"median. {points} points in the sweep.",
                    cite,
                )
            )
            bound = (
                ""
                if g.saturated
                else " The sweep had not saturated at its largest message, so this "
                "is a lower bound on the asymptote rather than the asymptote; it "
                "overstates transfer time, which is the safe direction."
            )
            out.append(
                entry(
                    f"collective_peak_rate_{stem}",
                    round(g.peak_bytes_per_us, 1),
                    "bytes_per_us",
                    chip,
                    f"{g.peak_bytes_per_us / 1000:.2f} GB/s, the maximum of "
                    f"message_size over latency across {points} points. Used as a "
                    f"ceiling on achievable bandwidth rather than as the rate itself: "
                    f"see collective_transition_rate_{stem}.{bound}",
                    cite,
                )
            )
            out.append(
                entry(
                    f"collective_transition_rate_{stem}",
                    round(g.transition_rate, 1),
                    "bytes_per_us",
                    chip,
                    f"{g.transition_rate / 1000:.2f} GB/s, the rate in "
                    f"max(floor + size / rate, size / peak). Fitted over {points} "
                    f"points by minimising the mean absolute log ratio, which weighs an "
                    f"under-prediction and an over equally. It cuts this "
                    f"configuration's geometric error from "
                    f"{g.error_two_param:.3f}x under the two-parameter form to "
                    f"{g.error_three_param:.3f}x. Below the asymptote, which is "
                    f"{g.transition_rate / g.peak_bytes_per_us:.2f} of it, because a "
                    f"collective reaches its asymptotic bandwidth only at messages far "
                    f"larger than one forward pass produces.",
                    cite,
                    fitted=True,
                )
            )
            total += 3
    out.append(f"\n# {total} entries generated.\n")
    sys.stdout.write("".join(out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
