#!/usr/bin/env python3
"""Generate the memory-occupancy coefficient set: activation scratch and CUDA-graph capture.

    emit_memory.py [--check]

Two families, from two sources, each stated in its own entries:

  * ACTIVATION SCRATCH, `vendor_spec`, from NVIDIA AISimulate's memory model. The
    live-buffer multiple per model family and tensor-parallel width is the
    `ACTIVATION_COEFFICIENTS` table in `sdk/backends/trtllm_backend.py`, which the vLLM
    backend reuses unchanged; the lower clamp is `MIN_ACTIVATION_BYTES` in
    `base_backend.py`. Both are read from the source with `ast`, never imported, so no
    AISimulate code runs here.
  * CUDA-GRAPH CAPTURE, `assumed`, anchored on vLLM's own start-up measurements, which
    `mine_vllm_cudagraph_memory.py` collected from the public issue tracker into
    `docs/vllm-cudagraph-capture-samples.csv`. That CSV is committed, so this half is
    reproducible without the network.

The AISimulate source is located from $AISIMULATE_DATA (the sweep tree every other writer
reads), whose grandparent is `aisimulate_core`. `--check` re-renders and exits non-zero if
the committed file would change.
"""

from __future__ import annotations

import ast
import csv
import os
import statistics
import sys
import textwrap
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
TARGET = REPO / "coefficients" / "cost-model-memory.yaml"
SAMPLES = REPO / "docs" / "vllm-cudagraph-capture-samples.csv"
# The vendored chip descriptors are the catalog's part list as this repository pins it, so
# the scope is deterministic in CI and a new part is a visible edit here.
PARTS = sorted(p.stem for p in (REPO / "validator/testdata/catalog/hardware").glob("*.yaml"))
DATA = Path(os.environ.get(
    "AISIMULATE_DATA", "/tmp/aisim/python/aisimulate/src/aisimulate_core/systems/data"))
CORE = DATA.parent.parent

# AISimulate's table is keyed by family. The kernel can tell only whether a model routes
# tokens to experts, so two rows are registered: the LLAMA row for dense models (Llama,
# Qwen2, Qwen3 and MiMo all map to it, which covers every dense model the catalog holds
# but one) and the MOE row, which every MoE family in the table shares.
FAMILIES = {"dense": "LLAMA", "moe": "MOE"}
WIDTHS = (1, 2, 4, 8)

# Accelerator names as the mined logs spell them, restricted to parts the catalog holds.
# A consumer GPU's capture runs a smaller model at a smaller capture list, so pooling it
# would describe deployments this registry is never asked to price.
CATALOG_GPUS = {"A100", "H100", "H200", "B200", "B300", "GB200", "GB300", "L40S"}

HEADER = '''\
# Memory occupancy — the per-rank bytes a deployment holds beyond weights and KV cache.
#
# GENERATED by scripts/emit_memory.py. Re-run it and commit the diff rather than editing
# values here; `emit_memory.py --check` is the drift gate.
#
# WHY A SEPARATE SET. These are magnitudes a CAPACITY verdict composes -- how many
# sequences fit -- not terms of step time, and before this set existed a consumer carried
# them as constants in its own source, where no provenance readout could see them. They
# are kept apart from cost-model-primitives.yaml because that set is single-sourced from
# AISimulate measurements and descriptors per part, and the capture figures here are
# anchored on a different source and are hardware-independent.
#
# TWO PROVENANCES, stated per entry rather than uniform across the set:
#
#   activation_buffer_count_<family>_<N>rank, activation_scratch_floor_bytes -- vendor_spec.
#   NVIDIA's own memory model (AISimulate sdk/backends), the figures its capacity estimate
#   charges. NVIDIA tuned them, this project did not measure them.
#
#   cudagraph_capture_bytes_<mode> -- assumed. The dimension is vLLM's own accounting; the
#   magnitude is the median of vLLM start-up logs, which are real measurements of
#   uncontrolled deployments. Each entry states n, the spread, and the one start-up log
#   line that would replace it for a given deployment.
#
# HOW THE TERMS COMPOSE, which is what a consumer needs and what AISimulate's capacity
# path (aisimulate_core/sdk/memory.py) does. Per rank, outside the KV budget:
#
#   weights + activation + nccl_communicator_bytes_<N>rank + engine_workspace_bytes
#           + cudagraph_capture_bytes_<mode>
#
# Every term ADDS. nccl_communicator_bytes_<N>rank is the whole collective-buffer
# reservation, and engine_workspace_bytes (AISimulate's misc.other_mem: CUDA context,
# cuBLAS and allocator slack) is a separate allowance beside it -- not part of it, and not
# containing the graph capture either: AISimulate annotates other_mem as excluding the
# CUDA-graph reservation (support/config_profile.py) and takes that reservation as its own
# argument (capacity.py, cuda_graph_reserved_bytes). Both of those stay in
# cost-model-primitives.yaml, because NVIDIA's descriptor states them per part.
#
# activation = max(activation_buffer_count_<family>_<N>rank * max_num_batched_tokens * h * 2,
#                  activation_scratch_floor_bytes)
#
# where h = num_attention_heads * head_dim, which is hidden_size unless the model config
# declares a head_dim that differs (AISimulate sdk/utils.py), and 2 is the bf16 width of
# the activations themselves. That width is the MODEL dtype, not the served weight dtype:
# vLLM's fp8 and nvfp4 linear kernels quantize their input transiently and return
# out_dtype=x.dtype (vllm/model_executor/kernels/linear/scaled_mm/cutlass.py), so an fp8
# deployment's residual stream and inter-layer buffers stay at bf16. N is min(tp, 8),
# because AISimulate clamps there.
#
# ENGINE. These are the vLLM figures. AISimulate's SGLang backend carries a table 1.3x
# higher (dense 14/8.5/6.5/6.5, MoE 28/17/13/13), a further 15% activation and 20% other-
# memory overhead, a 90 MiB floor, and does not charge activations inside its static pool
# at all. They are not registered: a deployment states no engine identity and the
# consumer prices vLLM, so an SGLang row would have no reader.
kind: CoefficientSet
name: cost-model-memory

coefficients:
'''


def scope() -> str:
    return "{hardware: [" + ", ".join(PARTS) + "]}"


def render(name: str, value, units: str, method: str, cites: list[tuple[str, str, str]],
           rationale: str) -> str:
    out = [
        f"  - {name}:",
        f"      value: {value}",
        f"      units: {units}",
        f"      method: {method}",
        "      fitted: false",
        f"      scope: {scope()}",
        "      sources:",
    ]
    for kind, cite, role in cites:
        out += [f"        - kind: {kind}", f'          cite: "{cite}"', f"          role: {role}"]
    out.append("      rationale: >")
    paras = [p for p in (" ".join(p.split()) for p in rationale.split("\n\n")) if p]
    for i, para in enumerate(paras):
        if i:
            out.append("")  # a blank line in a folded scalar keeps the paragraph break
        out += textwrap.wrap(para, width=88, initial_indent=" " * 8,
                             subsequent_indent=" " * 8, break_on_hyphens=False)
    return "\n".join(out) + "\n"


# --- activation scratch, from AISimulate's source -------------------------------------

def class_assignments(path: Path, cls: str) -> dict[str, ast.expr]:
    tree = ast.parse(path.read_text())
    for node in tree.body:
        if isinstance(node, ast.ClassDef) and node.name == cls:
            out = {}
            for stmt in node.body:
                if isinstance(stmt, ast.AnnAssign) and isinstance(stmt.target, ast.Name):
                    out[stmt.target.id] = stmt.value
                elif isinstance(stmt, ast.Assign):
                    for t in stmt.targets:
                        if isinstance(t, ast.Name):
                            out[t.id] = stmt.value
            return out
    raise SystemExit(f"{path}: no class {cls}")


def constant(expr: ast.expr):
    """Evaluate a literal or a product of literals, which is all these knobs are."""
    if isinstance(expr, ast.BinOp) and isinstance(expr.op, ast.Mult):
        return constant(expr.left) * constant(expr.right)
    return ast.literal_eval(expr)


def activation_source() -> tuple[dict[str, dict[int, float]], int]:
    backends = CORE / "sdk" / "backends"
    if not (backends / "trtllm_backend.py").is_file():
        raise SystemExit(
            f"AISimulate source not found under {CORE} (from AISIMULATE_DATA={DATA}). "
            f"Re-fetch with `git clone https://github.com/ai-dynamo/aisimulate`.")
    vllm = class_assignments(backends / "vllm_backend.py", "VLLMBackend")
    # Refuse rather than mislabel: the registered figures are the vLLM backend's, and
    # they are TRT-LLM's table only while vLLM aliases it.
    alias = vllm.get("ACTIVATION_COEFFICIENTS")
    if not (isinstance(alias, ast.Attribute) and alias.attr == "ACTIVATION_COEFFICIENTS"
            and isinstance(alias.value, ast.Name) and alias.value.id == "TRTLLMBackend"):
        raise SystemExit("VLLMBackend no longer aliases TRTLLMBackend's activation table; "
                         "read its own table instead of relabelling TRT-LLM's.")
    if "MIN_ACTIVATION_BYTES" in vllm:
        raise SystemExit("VLLMBackend now overrides MIN_ACTIVATION_BYTES; read it.")
    table = constant(class_assignments(backends / "trtllm_backend.py", "TRTLLMBackend")
                     ["ACTIVATION_COEFFICIENTS"])
    floor = constant(class_assignments(backends / "base_backend.py", "BaseBackend")
                     ["MIN_ACTIVATION_BYTES"])
    return table, int(floor)


def number(v: float):
    return int(v) if float(v).is_integer() else v


def activation_entries() -> list[str]:
    table, floor = activation_source()
    cite = [("model", "NVIDIA AISimulate aisimulate_core/sdk/backends/trtllm_backend.py "
             "TRTLLMBackend.ACTIVATION_COEFFICIENTS, reused by vllm_backend.py VLLMBackend",
             "primary")]
    moe_families = sorted(f for f, row in table.items()
                          if f != "default" and row == table["MOE"])
    out = []
    for family, row_name in FAMILIES.items():
        row = table[row_name]
        for n in WIDTHS:
            if family == "dense":
                which = (
                    f"the {row_name} row, which AISimulate applies to Llama, Qwen2, Qwen3 and "
                    f"MiMo. Its default row, used for any other dense architecture, is "
                    f"{number(table['default'][n])} at this width.")
            else:
                which = (
                    f"the MOE row, shared by every MoE family the table lists: "
                    f"{', '.join(moe_families)}. AISimulate adds a block-scale dispatch "
                    f"workspace on top for the DeepSeek-derived families and KIMIK25 "
                    f"(tokens * h * num_experts * top_k / ep / 128 * 4 bytes); that term is "
                    f"NOT in this multiple. Hybrid MoE families absent from the table "
                    f"(Qwen3.5, MiniMax-M3, Llama-4, Kimi-K3, Nemotron-H) fall to its dense "
                    f"default row in AISimulate, and the source flags the MoE row itself: \"based on "
                    f"TRT-LLM measurement with traditional MoE; fine-grained MoE may need "
                    f"re-study\".")
            wider = (" Widths above 8 take this value, as AISimulate clamps min(tp, 8)."
                     if n == 8 else "")
            out.append(render(
                f"activation_buffer_count_{family}_{n}rank", number(row[n]), "dimensionless",
                "vendor_spec", cite,
                f"""
                The live-buffer multiple of activation scratch for a {family} model at
                {n}-rank tensor parallelism: per rank, activation bytes are
                max(this * max_num_batched_tokens * h * 2, activation_scratch_floor_bytes),
                with h = num_attention_heads * head_dim and 2 the bf16 activation width (the
                set header gives the form and why the width is the model dtype, not the
                served one).{wider}

                From NVIDIA AISimulate's memory model: {which}

                vendor_spec rather than measured: NVIDIA's simulator charges it, its source
                says it was tuned against TRT-LLM measurement, and the vLLM backend reuses
                it "until a vLLM-specific tuning lands". This project measured nothing.
                It replaces a hardcoded 4 that a consumer carried as "a few live buffers",
                which undercounts every row of this table.

                NOT scoped by graph mode, deliberately: vLLM measures this peak in an eager
                profile run and accounts capture separately (gpu_worker.py,
                determine_available_memory), so graph memory is cudagraph_capture_bytes_<mode>
                and scoping this by mode would charge it twice. NOT scoped by hardware: the
                source states no per-part value, and the scope lists every catalog part for
                that reason.
                """))
    out.append(render(
        "activation_scratch_floor_bytes", floor, "bytes_per_rank", "vendor_spec",
        [("model", "NVIDIA AISimulate aisimulate_core/sdk/backends/base_backend.py "
          "BaseBackend.MIN_ACTIVATION_BYTES, not overridden by VLLMBackend", "primary")],
        f"""
        The lower clamp on activation scratch, {floor // 2**20} MiB per rank: activation
        bytes are max(activation_buffer_count_<family>_<N>rank * max_num_batched_tokens *
        h * 2, this). It binds only at a small token budget -- for h = 4096 at the dense
        8-rank multiple of 5 the product falls below it under
        {floor // (5 * 4096 * 2):,} tokens -- and is recorded so that a consumer
        reproducing NVIDIA's form does not have to rediscover it. vendor_spec: NVIDIA's
        figure, which its vLLM backend inherits unchanged (SGLang raises it to 90 MiB).
        """))
    return out


# --- CUDA-graph capture, from the committed vLLM log samples ---------------------------

def samples() -> list[dict]:
    with SAMPLES.open() as f:
        return list(csv.DictReader(f))


def capture_stats(rows: list[dict], mode: str, catalog_only: bool = True):
    vals = sorted(float(r["capture_gib"]) for r in rows
                  if r["mode"] == mode and (r["gpu"] in CATALOG_GPUS or not catalog_only))
    if not vals:
        return None
    q = lambda p: vals[min(len(vals) - 1, int(p * len(vals)))]
    parts = sorted({r["gpu"] for r in rows if r["mode"] == mode and r["gpu"] in CATALOG_GPUS})
    return {"n": len(vals), "median": statistics.median(vals), "p25": q(0.25),
            "p75": q(0.75), "parts": parts}


def mib_bytes(gib: float) -> int:
    return round(gib * 1024) * 2**20


CAPTURE_DIMENSION = """
DIMENSION, from vLLM's own accounting. vLLM measures a capture as a free-memory delta
and, since v0.21, subtracts it from the KV budget by default
(VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS; vllm/v1/worker/gpu_worker.py). Its profiler
(gpu_model_runner.py, profile_cudagraph_memory) prices each runtime mode as one FIRST
capture -- the largest shape, captured first, which sizes the shared graph pool -- plus
a per-graph increment of at least 1 MiB for every further shape, and overlays PIECEWISE
and FULL in one pool by taking the larger first capture. So the cost is dominated by the
largest captured shape, not proportional to the number of shapes: the constant this
replaces was justified as "one buffer set per captured shape", which is not how vLLM
allocates.
"""

CAPTURE_LIMIT = """
KNOWN LIMITATION. A flat per-rank figure. The real one grows with
max_cudagraph_capture_size and with the model's width, and shrinks somewhat with tensor
parallelism; no scope dimension can carry those, so a deployment far from the median
model size is far from this figure in either direction. Each sample is a different
model and capture list, so the spread is variation ACROSS deployments, not noise around
one value.

TO REPLACE THIS WITH A MEASUREMENT. Start the target deployment once and read vLLM's own
log: "CUDA graph pool memory: X GiB (actual)" on v0.21 and later, or "Graph capturing
finished in S secs, took X GiB" before it. One start-up, no benchmark, and the number
is per rank.
"""


def capture_entries() -> list[str]:
    rows = samples()
    cite_logs = ("discussion",
                 "vLLM start-up logs in vllm-project/vllm issues, collected by "
                 "scripts/mine_vllm_cudagraph_memory.py into "
                 "docs/vllm-cudagraph-capture-samples.csv",
                 "supporting")
    cite_src = ("discussion",
                "vllm/v1/worker/gpu_model_runner.py profile_cudagraph_memory and "
                "vllm/v1/worker/gpu_worker.py, the accounting the dimension is taken from",
                "supporting")
    out = []
    measured = {}
    for mode in ("PIECEWISE", "FULL_AND_PIECEWISE"):
        s = capture_stats(rows, mode)
        if s is None:
            raise SystemExit(f"{SAMPLES}: no {mode} sample on a catalog part to anchor on")
        measured[mode] = s
        extra = ("" if mode == "PIECEWISE" else
                 " It cannot be below the PIECEWISE figure for the same deployment: it "
                 "captures the PIECEWISE set and the FULL decode set into one overlaid "
                 "pool, so it pays the larger first capture plus both sets' per-graph "
                 "increments.")
        out.append(render(
            f"cudagraph_capture_bytes_{mode.lower()}", mib_bytes(s["median"]),
            "bytes_per_rank", "assumed", [cite_logs, cite_src],
            f"""
            Device memory a {mode} CUDA-graph capture holds per rank, outside the KV
            budget.{extra}

            {CAPTURE_DIMENSION}

            MAGNITUDE (orientation only -- THIS IS THE CAVEAT). {s['median']:.2f} GiB is
            the median of {s['n']} vLLM start-up logs on catalog parts
            ({', '.join(s['parts'])}) whose mode is {mode}, stated in the log or vLLM's
            default for the stated version; the interquartile range is {s['p25']:.2f} to
            {s['p75']:.2f} GiB. The constant it replaces was 0.50 GiB, below the median.
            These are vLLM's own measurements, but of uncontrolled deployments, which is
            why this is assumed and not measured.

            {CAPTURE_LIMIT}
            """))
    bound = measured["FULL_AND_PIECEWISE"]
    for mode in ("FULL", "FULL_DECODE_ONLY"):
        any_part = capture_stats(rows, mode, catalog_only=False)
        on_parts = capture_stats(rows, mode)
        seen = (f"{any_part['n']} log(s) state this mode, "
                f"{on_parts['n'] if on_parts else 0} on a catalog part, median "
                f"{any_part['median']:.2f} GiB" if any_part else "no log states this mode")
        out.append(render(
            f"cudagraph_capture_bytes_{mode.lower()}", mib_bytes(bound["median"]),
            "bytes_per_rank", "assumed", [cite_logs, cite_src],
            f"""
            Device memory a {mode} CUDA-graph capture holds per rank, CHARGED AT THE
            FULL_AND_PIECEWISE FIGURE AS AN UPPER BOUND. {seen} -- too few to anchor a
            median. The bound is structural: {mode} captures a subset of the graphs
            FULL_AND_PIECEWISE does, into the same overlaid pool, so for one deployment
            it cannot cost more. DECLARED DIRECTION: this OVERSTATES, which for a capacity
            verdict errs toward admitting fewer sequences rather than more.

            {CAPTURE_DIMENSION}

            {CAPTURE_LIMIT}
            """))
    out.append(render(
        "cudagraph_capture_bytes_none", 0, "bytes_per_rank", "not_charged", [cite_src],
        """
        No capture, so no capture memory: under cudagraph_mode NONE vLLM skips both the
        memory profile (gpu_worker.py) and the capture (gpu_model_runner.py,
        capture_model returns 0). Recorded
        as a deliberate zero so that an eager deployment reads "no cost" rather than "cost
        unknown", and so that every mode a consumer can be given has an entry to resolve.
        """))
    return out


def generate() -> str:
    entries = activation_entries() + capture_entries()
    return HEADER + "".join(entries) + f"\n# {len(entries)} entries generated.\n"


def main(argv: list[str]) -> int:
    text = generate()
    if argv[1:] == ["--check"]:
        if TARGET.read_text() != text:
            print(f"{TARGET} differs from what emit_memory.py generates", file=sys.stderr)
            return 1
        return 0
    if argv[1:]:
        print(__doc__, file=sys.stderr)
        return 2
    TARGET.write_text(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
