#!/usr/bin/env python3
"""Generate the per-SKU primitive coefficient set from NVIDIA AISimulate.

Two kinds of number, both from NVIDIA and nothing else:

  * FITTED, from the measurement sweeps — the GEMM efficiency envelope per dtype
    and the MoE routing-imbalance order statistics.
  * DECLARED, from AISimulate's own system descriptors (systems/<sku>.yaml) — the
    HBM derate, the memory-access floor, the PCIe host-link bandwidth, the NCCL
    communicator reservation per rank count, and the p2p latency.

The declared group matters as much as the fitted one. Those are numbers NVIDIA
ships with its own simulator, annotated there as corrections based on observation,
and three of them replace figures this model previously carried as assumptions: the
communicator buffer size, the CUDA-graph and workspace allowance, and the host
link rate.

Usage:
    python scripts/emit_primitives.py <aisimulate>/systems <catalog-root> > \
        coefficients/cost-model-primitives.yaml

The first argument is the `systems` directory, which holds both the per-SKU
descriptors (`<sku>.yaml`) and the measurement collections (`data/<sku>/...`).
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import yaml

_spec = importlib.util.spec_from_file_location(
    "fit_gemm_envelope", Path(__file__).parent / "fit_gemm_envelope.py"
)
fg = importlib.util.module_from_spec(_spec)
assert _spec.loader is not None
_spec.loader.exec_module(fg)

HEADER = '''# Cost-model primitives — every entry from NVIDIA AISimulate.
#
# GENERATED by scripts/emit_primitives.py. Re-run after an AISimulate data update
# and commit the diff rather than editing values here.
#
# Two kinds of number, both NVIDIA-sourced:
#
#   FITTED, from the measurement sweeps. The GEMM efficiency envelope
#   eff(M) = eps_max * M / (M + M_half), fitted per dtype against the per-M
#   envelope of achieved fraction of that dtype's dense peak; and the MoE
#   routing-imbalance multiplier, as order statistics of paired measurements that
#   differ in nothing but the routing distribution.
#
#   DECLARED, from AISimulate's own system descriptors (systems/<sku>.yaml). These
#   are numbers NVIDIA ships with its simulator, annotated there as corrections
#   based on observation. They are recorded as `vendor_spec` rather than
#   `measured`: NVIDIA observed them, this project did not, and the sweep behind
#   them is not published.
#
# The envelope is per SKU as well as per dtype, and the H100/H200 pair shows why
# it has to be. Those two share the GH100 die and therefore an identical compute
# peak, and their asymptotes agree to within 0.013 as that predicts. Their knees
# do not: M_half is 160 on H100 and 102 on H200, a factor of 1.57. The knee is set
# by how fast operands reach the tensor cores, so it tracks memory bandwidth
# (3.35 against 4.8 TB/s) rather than compute. A model that carries one part's
# ramp to another on shared-die reasoning gets the asymptote right and the knee
# wrong, and the knee is what governs every decode-sized batch.
kind: CoefficientSet
name: cost-model-primitives

coefficients:
'''

DTYPE_SUFFIX = {
    "bfloat16": "bf16",
    "float16": "fp16",
    "fp8": "fp8",
    "fp8_block": "fp8_block",
    "nvfp4": "nvfp4",
}

# Which measurement collection each SKU's coefficients come from, pinned by name.
#
# Pinned rather than selected by a rule, for two reasons the data forces. First,
# "newest version" is wrong: h200's moe has trtllm 1.3.0rc10, rc20 and rc23 with
# 24 786, 42 174 and 3 564 paired shapes respectively, and their medians read
# 1.103, 1.056 and 1.002. The newest is the smallest and least representative.
# Second, "largest collection" is also wrong: it picks vLLM for GEMM and TRT-LLM
# for MoE on the same part, so a cross-SKU comparison would confound hardware with
# runtime.
#
# TRT-LLM 1.3.0rc20 carries both families for h100, h200, l40s and gb200, which
# makes those four directly comparable under one runtime. A100 predates it and has
# no equivalent, so it is pinned to what exists and the difference is stated in
# every A100 entry's rationale rather than hidden. a100_pcie has no measurement
# collection at all and therefore gets no fitted coefficients.
COLLECTIONS = {
    "h100_sxm": {"gemm": "trtllm/1.3.0rc20", "moe": "trtllm/1.3.0rc20"},
    "h200_sxm": {"gemm": "trtllm/1.3.0rc20", "moe": "trtllm/1.3.0rc20"},
    # Blackwell pins the same trtllm collection as Hopper, so an envelope difference
    # between the two is the silicon rather than a framework version.
    "b200_sxm": {"gemm": "trtllm/1.3.0rc20", "moe": "trtllm/1.3.0rc20"},
    "b300_sxm": {"gemm": "trtllm/1.3.0rc20", "moe": "trtllm/1.3.0rc20"},
    "l40s": {"gemm": "trtllm/1.3.0rc20", "moe": "trtllm/1.3.0rc20"},
    "gb200": {"gemm": "trtllm/1.3.0rc20", "moe": "trtllm/1.3.0rc20"},
    # A100 predates the rc20 sweeps. sglang/0.5.10 is the most complete collection
    # that exists for this part, and it is a different runtime from the other four,
    # so its numbers are not strictly comparable with theirs.
    "a100_sxm": {"gemm": "sglang/0.5.10", "moe": "sglang/0.5.10"},
}

# The runtime every cross-SKU comparison in this set is made under. An entry from
# a different collection says so in its rationale.
REFERENCE_COLLECTION = "trtllm/1.3.0rc20"

# AISimulate SKU directory to its system descriptor and catalog chip.
SKUS = fg.SKU_TO_CHIP


def entry(
    name: str,
    value,
    units: str,
    method: str,
    chip: str,
    cite: str,
    rationale: str,
    fitted: bool = False,
    ci95: tuple[float, float] | None = None,
) -> str:
    out = (
        f"  - {name}:\n"
        f"      value: {value}\n"
        f"      units: {units}\n"
        f"      method: {method}\n"
        f"      fitted: {'true' if fitted else 'false'}\n"
        f"      scope: {{hardware: [{chip}]}}\n"
    )
    if ci95:
        out += f"      ci95: [{ci95[0]}, {ci95[1]}]\n"
    out += (
        f"      sources:\n"
        f"        - {{kind: model, cite: \"{cite}\", role: primary}}\n"
        f"      rationale: >\n"
        f"        {rationale}\n"
    )
    return out


def gemm_entries(root: Path, catalog: Path, sku: str, chip: str) -> list[str]:
    pinned = COLLECTIONS.get(sku, {}).get("gemm")
    if pinned is None:
        return []
    version = root / "data" / sku / "gemm" / pinned
    if not version.is_dir():
        raise FileNotFoundError(
            f"{sku}: pinned GEMM collection {pinned} is absent; update COLLECTIONS "
            f"rather than falling back to another one silently"
        )
    rows = fg.read_rows(version, "gemm_perf")
    if rows is None:
        return []
    peaks = fg.peaks_from_catalog(catalog, chip)
    device = rows[0]["device"]
    measured = {r["gemm_dtype"] for r in rows}
    out = []
    for dtype, suffix in DTYPE_SUFFIX.items():
        if dtype not in measured or dtype not in peaks:
            continue
        env = fg.envelope(rows, dtype, peaks[dtype])
        if not env:
            continue
        eps, m_half, rms = fg.fit_ramp(env)
        n = sum(1 for r in rows if r["gemm_dtype"] == dtype)
        cite = (
            f"NVIDIA AISimulate systems/data/{sku}/gemm/{pinned}/gemm_perf.parquet "
            f"({device})"
        )
        offref = (
            ""
            if pinned == REFERENCE_COLLECTION
            else f" Measured under {pinned} rather than the "
            f"{REFERENCE_COLLECTION} the other parts in this set use, because no "
            f"{REFERENCE_COLLECTION} collection exists for it; the value is "
            f"therefore not strictly comparable with theirs."
        )
        ceiling = ""
        if eps >= 1.0:
            ceiling = (
                " The asymptote is pinned at peak: the two-parameter ramp "
                "extrapolates past the highest observed fraction "
                f"({max(env.values()):.3f}), so this part's envelope is better "
                "read as approaching peak than as having a fitted ceiling."
            )
        out.append(
            entry(
                f"gemm_eps_max_{suffix}",
                round(eps, 3),
                "dimensionless",
                "measured",
                chip,
                cite,
                f"Least-squares fit of eff = eps_max * M / (M + M_half) to the "
                f"per-M efficiency envelope of {n} {dtype} rows against this "
                f"part's dense {dtype} peak, over {len(env)} distinct M. RMS "
                f"residual {rms:.3f}, which is the interval. Highest single "
                f"observation {max(env.values()):.3f}.{ceiling}{offref}",
                fitted=True,
                ci95=(round(max(0.0, eps - rms), 3), round(min(1.0, eps + rms), 3)),
            )
        )
        out.append(
            entry(
                f"gemm_m_half_{suffix}",
                m_half,
                "tokens",
                "measured",
                chip,
                cite,
                f"The half-max row count from the same fit as "
                f"gemm_eps_max_{suffix}.",
                fitted=True,
            )
        )
    return out


def moe_entries(root: Path, sku: str, chip: str) -> list[str]:
    pinned = COLLECTIONS.get(sku, {}).get("moe")
    if pinned is None:
        return []
    version = root / "data" / sku / "moe" / pinned
    if not version.is_dir():
        raise FileNotFoundError(
            f"{sku}: pinned MoE collection {pinned} is absent; update COLLECTIONS "
            f"rather than falling back to another one silently"
        )
    rows = fg.read_rows(version, "moe_perf")
    if rows is None:
        return []

    def shape(r: dict) -> tuple:
        return tuple(
            r[k] for k in (
                "moe_dtype", "num_tokens", "hidden_size", "inter_size", "topk",
                "num_experts", "moe_tp_size", "moe_ep_size", "kernel_source",
            )
        )

    balanced = {
        shape(r): r["latency"] for r in rows if r["distribution"] == "balanced"
    }
    ratios = sorted(
        r["latency"] / balanced[shape(r)]
        for r in rows
        if r["distribution"] == "power_law_1.01"
        and shape(r) in balanced
        and balanced[shape(r)] > 0
    )
    if len(ratios) < 100:
        return []
    n = len(ratios)
    median = ratios[n // 2]
    p10, p90 = ratios[int(0.10 * n)], ratios[int(0.90 * n)]
    cite = (
        f"NVIDIA AISimulate systems/data/{sku}/moe/{pinned}/moe_perf.parquet, "
        f"distribution power_law_1.01 against balanced ({rows[0]['device']})"
    )
    offref = (
        ""
        if pinned == REFERENCE_COLLECTION
        else f" Measured under {pinned} rather than the {REFERENCE_COLLECTION} the "
        f"other parts in this set use, so not strictly comparable with theirs."
    )
    return [
        entry(
            "moe_routing_imbalance_median", round(median, 3), "dimensionless",
            "measured", chip, cite,
            f"Ratio of measured latency under a power-law routing distribution to "
            f"the same shape under a balanced one, over {n} shapes differing in "
            f"nothing but the distribution. Median {median:.3f}; the interval is "
            f"the 10th and 90th percentiles and the maximum observed is "
            f"{ratios[-1]:.1f}. The spread is the finding: at the median a skewed "
            f"distribution costs a few percent and at the 90th percentile tens of "
            f"percent, so a prediction sensitive to this term should carry the "
            f"band rather than a point. Not marked fitted: an order statistic of "
            f"measured ratios, not a curve fit.{offref}",
            ci95=(round(p10, 3), round(p90, 3)),
        ),
        entry(
            "moe_routing_imbalance_p90", round(p90, 3), "dimensionless", "measured",
            chip, cite,
            f"The 90th percentile of the same {n} ratios, quoted separately so a "
            f"conservative estimate can use it directly.{offref}",
        ),
    ]


def descriptor_entries(root: Path, sku: str, chip: str) -> list[str]:
    path = root / f"{sku}.yaml"
    if not path.is_file():
        return []
    d = yaml.safe_load(path.read_text())
    gpu, node, misc = d.get("gpu", {}), d.get("node", {}), d.get("misc", {})
    cite = f"NVIDIA AISimulate systems/{sku}.yaml"
    out = []
    if (derate := gpu.get("mem_bw_empirical_scaling_factor")) is not None:
        out.append(entry(
            "hbm_derate", derate, "dimensionless", "vendor_spec", chip, cite,
            "The fraction of datasheet HBM bandwidth a real access stream "
            "achieves. NVIDIA ships this in its own system descriptor, annotated "
            "there as a correction based on observation. Applied to the catalog's "
            "BwPeakTBs. vendor_spec rather than measured: NVIDIA observed it, this "
            "project did not, and the sweep behind it is not published.",
        ))
    if (lat := gpu.get("mem_empirical_constant_latency")) is not None:
        out.append(entry(
            "hbm_constant_latency", round(lat * 1e6, 2), "us_per_transfer",
            "vendor_spec", chip, cite,
            "A fixed floor on any memory access, below which a transfer's size "
            "stops mattering. At batch 32 the HBM term is milliseconds and this is "
            "noise, but for a small elementwise kernel it dominates.",
        ))
    if (pcie := node.get("pcie_bw")) is not None:
        out.append(entry(
            "host_link_bandwidth", round(pcie / 1e6, 1), "bytes_per_us",
            "vendor_spec", chip, cite,
            f"{pcie / 1e9:.0f} GB/s single-direction over the CPU-to-GPU link, "
            f"which is what an offload tier's transfer crosses in addition to host "
            f"memory. NVIDIA's descriptor states this per part, and the value "
            f"differs by platform: a Grace-Blackwell part connects over NVLink-C2C "
            f"rather than PCIe, so a tier that is a liability on one host can be "
            f"affordable on another. Nominal link rate, not a measured payload "
            f"throughput; a real transfer reaches a fraction of it.",
        ))
    if (p2p := node.get("p2p_latency")) is not None:
        out.append(entry(
            "p2p_latency", round(p2p * 1e6, 2), "us_per_hop", "vendor_spec", chip,
            cite,
            "Point-to-point latency between two GPUs, which NVIDIA's descriptor "
            "carries as a single per-part figure. The measured per-operation "
            "collective floors in cost-model-collectives supersede this for "
            "pricing a collective; it is recorded because it is the figure "
            "NVIDIA's own model uses, so a comparison against that model needs it.",
        ))
    nccl_mem = misc.get("nccl_mem") or {}
    for ranks in sorted(k for k in nccl_mem if isinstance(k, int)):
        if not nccl_mem[ranks]:
            continue
        out.append(entry(
            f"nccl_communicator_bytes_{ranks}rank", nccl_mem[ranks], "bytes_per_rank",
            "vendor_spec", chip, cite,
            f"Bytes a rank reserves for NCCL communicator buffers at {ranks} "
            f"ranks, from NVIDIA's descriptor. It enters the memory breakdown's "
            f"CommBuffers term, and it is a real per-rank-count figure rather than "
            f"the order-of-magnitude constant this model previously carried.",
        ))
    if (other := misc.get("other_mem")) is not None:
        out.append(entry(
            "engine_workspace_bytes", other, "bytes_per_rank", "vendor_spec", chip,
            cite,
            f"{other / 1e9:.1f} GB of non-weight, non-KV occupancy NVIDIA's "
            f"descriptor reserves, described there as covering CUDA-graph capture, "
            f"workspace and the inaccuracy of the rest of the memory calculation. "
            f"It is a lumped allowance rather than a decomposition, so the memory "
            f"breakdown reports it as one term and does not claim to split it.",
        ))
    return out


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    root, catalog = Path(argv[1]), Path(argv[2])
    out = [HEADER]
    total = 0
    for sku, chip in sorted(SKUS.items()):
        block = (
            gemm_entries(root, catalog, sku, chip)
            + moe_entries(root, sku, chip)
            + descriptor_entries(root, sku, chip)
        )
        if not block:
            continue
        out.append(f"\n  # --- {chip} ({sku}) ---\n")
        out.extend(block)
        total += len(block)
    out.append(f"\n# {total} entries generated.\n")
    sys.stdout.write("".join(out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
